-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 23:52:08 2017
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema oticaDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `oticaDB` ;

-- -----------------------------------------------------
-- Schema oticaDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oticaDB` ;
USE `oticaDB` ;

-- -----------------------------------------------------
-- Table `Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Endereco` ;

CREATE TABLE IF NOT EXISTS `Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `numero` INT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idEndereco_UNIQUE` ON `Endereco` (`idEndereco` ASC);


-- -----------------------------------------------------
-- Table `Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Cliente` ;

CREATE TABLE IF NOT EXISTS `Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `dataNascimento` DATE NULL,
  `idade` INT NULL,
  `RG` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `telResidencial` VARCHAR(45) NULL,
  `teleCelular` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `idEndereco` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_Cliente_Endereco`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCliente_UNIQUE` ON `Cliente` (`idCliente` ASC);

CREATE INDEX `fk_Cliente_Endereco_idx` ON `Cliente` (`idEndereco` ASC);


-- -----------------------------------------------------
-- Table `Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Produto` ;

CREATE TABLE IF NOT EXISTS `Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `armacao` VARCHAR(45) NULL,
  `lentes` VARCHAR(45) NULL,
  `valor_armacao` DOUBLE NULL,
  `valor_lente` DOUBLE NULL,
  `especificacoes` VARCHAR(200) NULL,
  PRIMARY KEY (`idProduto`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idProduto_UNIQUE` ON `Produto` (`idProduto` ASC);


-- -----------------------------------------------------
-- Table `Pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pagamento` ;

CREATE TABLE IF NOT EXISTS `Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `formaPagamento` INT NULL,
  `valorRestante` DOUBLE NULL,
  `qtdParcelas` INT NULL,
  `valorParcelas` DOUBLE NULL,
  `entrada` DOUBLE NULL,
  `cartao` VARCHAR(45) NULL,
  `bandeira` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Compra` ;

CREATE TABLE IF NOT EXISTS `Compra` (
  `idCliente` INT NOT NULL,
  `idProduto` INT NOT NULL,
  `valorTotal` DOUBLE NULL,
  `dataCompra` DATE NULL,
  `dataEntrega` DATE NULL,
  `dataVencimento` DATE NULL,
  `idPagamento` INT NOT NULL,
  PRIMARY KEY (`idCliente`, `idProduto`, `idPagamento`),
  CONSTRAINT `fk_Cliente_has_Produto_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Produto_Produto1`
    FOREIGN KEY (`idProduto`)
    REFERENCES `Produto` (`idProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_Pagamento1`
    FOREIGN KEY (`idPagamento`)
    REFERENCES `Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Cliente_has_Produto_Produto1_idx` ON `Compra` (`idProduto` ASC);

CREATE INDEX `fk_Cliente_has_Produto_Cliente1_idx` ON `Compra` (`idCliente` ASC);

CREATE INDEX `fk_Compra_Pagamento1_idx` ON `Compra` (`idPagamento` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
